# Generated by Django 6.0.1 on 2026-02-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=254)),
                ('total_prix', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PREPARATION', 'En préparation'), ('PRET', 'Prêt au retrait'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True, help_text='Liste des ingrédients pour les allergènes')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantite_info', models.CharField(blank=True, help_text='ex: 6 pièces', max_length=50)),
                ('image_vignette', models.URLField(blank=True, max_length=500, null=True)),
                ('image_grande', models.URLField(blank=True, max_length=500, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='api.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.commande')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produit')),
            ],
        ),
    ]
